import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Sans } from "next/font/google";
import "./globals.css";
import { DM_Sans } from "next/font/google";
import {
  COMPANY_BASE_URL,
  COMPANY_DESCRIPTION,
  COMPANY_NAME,
} from "@/constants/company";
import { metadataConfig } from "./metadata";
import AppProvider from "../providers/AppProvider/AppProvider";
// import Navbar from "@/components/shared/Navbar/Navbar";
// import Footer from "@/components/shared/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${DMSans.variable} antialiased w-full overflow-hidden bg-white dark:bg-black `}
      >
        <AppProvider>
          {/* <Navbar /> */}

          <div className="tracking-tight ">{children}</div>

          {/* <Footer /> */}
        </AppProvider>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </body>
    </html>
  );
}
